version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  bank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Bank
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres_data: